language: go

go:
  - 1.15.x
  - tip

go_import_path: github.com/kc596/priorityworkerpool

before_install:
  - go get -t -v ./...

script:
  - go test ./... -race -coverprofile=coverage.txt -covermode=atomic

after_success:
  - bash <(curl -s https://codecov.io/bash)

notifications:
  email:
    recipients:
      - chaudhary.kc.kunal@gmail.com
    on_success: never
    on_failure: always
